/* wallace: WaterManagement.as
 * ==============================================================================
 * (This code was generated by a tool)
 * ==============================================================================
 * This work has been carried out as part of the SEAMLESS Integrated Framework
 * project, EU 6th Framework Programme, contract no. 010036-2 and/or as part
 * of the SEAMLESS association.
 *
 * Copyright (c) 2009 The SEAMLESS Association.
 *
 * For more information: http://www.seamlessassociation.org;
 * email: info@seamless-if.org
 *
 * The contents of this file is subject to the SEAMLESS Association License for
 * software infrastructure and model components Version 1.1 (the "License");
 * you may not use this file except in compliance with the License. You may
 * obtain a copy of the License at http://www.seamlessassociation.org/License.htm
 *
 * Software distributed under the License is distributed on an "AS IS"  basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for
 * the specific governing rights and limitations.
 *
 * The Initial Developers of the Original Code are:
 *  - Benny Johnsson; Lund University
 *  - Rob Knapen; Alterra, Wageningen UR
 *  - Michiel Rop; Alterra, Wageningen UR / ilionX
 *  - Lorenzo Ruinelli; IDSIA Dalle Molle Institute for Artificial Intelligence
 * ================================================================================
 * Contributor(s): N/A
 * ================================================================================
 */
package org.seamless_ip.services.transferobjects.prodent
{
    import mx.collections.ArrayCollection;
    import org.seamless_ip.services.transferobjects.prodent.IManagementPractice;
	import org.seamless_ip.services.transferobjects.utils.IClonable;

	[Bindable]
	[RemoteClass(alias="org.seamless_ip.services.transferobjects.prodent.WaterManagementTO")]

	public class WaterManagement implements IClonable, IManagementPractice	{
		public function WaterManagement()
		{
			crops = new ArrayCollection();
		}	
			
		
		public var changeNutrientManagement: Boolean;
		public var crops: ArrayCollection;
		public var demandBasedIrrigation: Boolean;
		public var endDay: int;
		public var id: String;
		public var irrigationWaterVolume: Number;
		public var numberOfRepetitions: int;
		public var plantAvailableWaterThreshold: Number;
		public var potentialIrrigation: Boolean;
		public var startDay: int;
		public var userDefinedIrrigation: Boolean;





		public function Clone():IClonable
		{
			var clone: WaterManagement = new WaterManagement();
			var item:IClonable;  
			clone.changeNutrientManagement = this.changeNutrientManagement;
			for each (item in this.crops)
				clone.crops .addItem(item.Clone());
			clone.demandBasedIrrigation = this.demandBasedIrrigation;
			clone.endDay = this.endDay;
			clone.id = this.id;
			clone.irrigationWaterVolume = this.irrigationWaterVolume;
			clone.numberOfRepetitions = this.numberOfRepetitions;
			clone.plantAvailableWaterThreshold = this.plantAvailableWaterThreshold;
			clone.potentialIrrigation = this.potentialIrrigation;
			clone.startDay = this.startDay;
			clone.userDefinedIrrigation = this.userDefinedIrrigation;
			return clone;
		}
	}
	
	
}
