/* wallace: PICAassessment.as
 * ==============================================================================
 * (This code was generated by a tool)
 * ==============================================================================
 * This work has been carried out as part of the SEAMLESS Integrated Framework
 * project, EU 6th Framework Programme, contract no. 010036-2 and/or as part
 * of the SEAMLESS association.
 *
 * Copyright (c) 2009 The SEAMLESS Association.
 *
 * For more information: http://www.seamlessassociation.org;
 * email: info@seamless-if.org
 *
 * The contents of this file is subject to the SEAMLESS Association License for
 * software infrastructure and model components Version 1.1 (the "License");
 * you may not use this file except in compliance with the License. You may
 * obtain a copy of the License at http://www.seamlessassociation.org/License.htm
 *
 * Software distributed under the License is distributed on an "AS IS"  basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for
 * the specific governing rights and limitations.
 *
 * The Initial Developers of the Original Code are:
 *  - Benny Johnsson; Lund University
 *  - Rob Knapen; Alterra, Wageningen UR
 *  - Michiel Rop; Alterra, Wageningen UR / ilionX
 *  - Lorenzo Ruinelli; IDSIA Dalle Molle Institute for Artificial Intelligence
 * ================================================================================
 * Contributor(s): N/A
 * ================================================================================
 */
package org.seamless_ip.services.transferobjects.pica
{
    import org.seamless_ip.services.transferobjects.pica.CrucialInstitutionalAspect;
    import org.seamless_ip.services.transferobjects.pica.InstitutionalCompatibility;
	import org.seamless_ip.services.transferobjects.utils.IClonable;

	[Bindable]
	[RemoteClass(alias="org.seamless_ip.services.transferobjects.pica.PICAassessmentTO")]

	public class PICAassessment implements IClonable	{
		public function PICAassessment()
		{
		}	
			
		
		public var assessmentCrucialInstitutionalAspect: String;
		public var compatibilityStatement: String;
		public var crucialInstitutionalAspect: CrucialInstitutionalAspect;
		public var id: String;
		public var influenceCategory: String;
		public var ofInstitutionalCompatibility: InstitutionalCompatibility;
		public var rankThematicCategory: int;
		public var rankcrucialinstitutionalaspect: int;
		public var thematicCategory: String;





		public function Clone():IClonable
		{
			var clone: PICAassessment = new PICAassessment();
			var item:IClonable;  
			clone.assessmentCrucialInstitutionalAspect = this.assessmentCrucialInstitutionalAspect;
			clone.compatibilityStatement = this.compatibilityStatement;
			clone.crucialInstitutionalAspect = (CrucialInstitutionalAspect)(this.crucialInstitutionalAspect .Clone());
			clone.id = this.id;
			clone.influenceCategory = this.influenceCategory;
			clone.ofInstitutionalCompatibility = (InstitutionalCompatibility)(this.ofInstitutionalCompatibility .Clone());
			clone.rankThematicCategory = this.rankThematicCategory;
			clone.rankcrucialinstitutionalaspect = this.rankcrucialinstitutionalaspect;
			clone.thematicCategory = this.thematicCategory;
			return clone;
		}
	}
	
	
}
